### PR TITLE
:ledger: support no_std

### PR DESCRIPTION
**Pull request by alexkazik**

### CODE REVIEW

**Comment by alexkazik** [comment]
Update: this is not fully working yet. the debug derive does use Vec which is alloc but not no_std.

**Comment by alexkazik** [comment]
Now it should be totally no_std

**Comment by mokeyish** [comment]
thanks! @alexkazik

**Comment by mokeyish** [comment]
it has been released at https://crates.io/crates/enum-flags/0.4.0

**Pull request merged**
